### ISSUE TITLE
Webpack bundling Gridsome components even when unused on Storyblok page

### ISSUE THREAD

**Issue by Tarrah102** [storyblok/gridsome-source-storyblok#34]
I have a Gridsome website which pulls content in from Storyblok using `gridsome-source-storyblok`. 

The site has about 50 possible components that can be added from within Storyblok in order to build the page.

The components are registered in the main template and should only be loaded if they are getting used, however it seems that Webpack is bundling all of the Gridsome components, even when they're not being used on the Storyblok page.

This is my function for loading the components:

```js
// StoryblokEntry.vue
  mounted() {
    // ...
    for(let component of components) {
      this.$options.components[`${component}`] = require(`../components/${component}`).default
    }
    // ...
  }
```

This is my Webpack configuration:

```js
// gridsome.config.js
module.exports = {
  // ...
  plugins: [
  // ...
  chainWebpack(config) {
    config.resolve.alias.set('@storyblok', '@/media-storyblok')
    config.mode('production')
    // Load variables for all vue-files
    const types = ['vue-modules', 'vue', 'normal-modules', 'normal']
  }
}
```

Lighthouse is returning very low scores of just 25/100 for Performance with the suggestion to `Remove unused JavaScript` to save `5.85s` of load time.  The fix for this is clearly for Webpack to only bundle the Gridsome components when they're being used on the Storyblok page, but this does not seem possible(?).

![image](https://user-images.githubusercontent.com/15898755/102026226-56a08700-3de8-11eb-88bd-6b8c26ec5660.png)

I notice there is an unanswered StackOverflow question that seems like it could concern the same issues https://stackoverflow.com/questions/57972231/gridsome-vue-js-how-do-i-reduce-the-core-bundle-size

**Comment by x5hwuk7nc6jsudcc** [comment]
The have the same issue for our Gridsome-Storyblok sites even when using the method set out in the https://github.com/storyblok/storyblok-gridsome-boilerplate

**Comment by maoberlehner** [comment]
Hi @Tarrah102 and @x5hwuk7nc6jsudcc 

So first this:

```js
// StoryblokEntry.vue
mounted() {
  // ...
  for(let component of components) {
    this.$options.components[`${component}`] = require(`../components/${component}`).default
  }
  // ...
}
```

I don't know what exactly is happening here but I'm pretty sure this makes it impossible for your site to work in SSR mode because `mounted` is only executed client-side. So I don't even know why this works at all 😅

> It's the opposite to what should be happening and what is described as Gridsome's fast by default automatic code-splitting features.

I have no idea what this sentence on the gridsome.org page is supposed to mean.

> Every `import` you declare gets bundled and served with each page.

Isn't this the opposite of what you want: `served with each page`?

Anyway, here is the solution:

```js
// main.js
// This is the main.js file. Import global CSS and scripts here.
// The Client API can be used here. Learn more: gridsome.org/docs/client-api

import DefaultLayout from '~/layouts/Default.vue'
import Page from '~/components/Page.vue'

export default function (Vue, { router, head, isClient }) {
  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)

  Vue.component('Page', Page)
  Vue.component('Teaser', () => import('~/components/Teaser.vue'))
  Vue.component('Feature', () => import('~/components/Feature.vue'))
  Vue.component('Grid', () => import('~/components/Grid.vue'))
  Vue.component('Richtext',() => import('~/components/Richtext.vue'))
  Vue.component('MyImage', () => import('~/components/MyImage.vue'))
}
```

For code-splitting to work, you need to use *dynamic imports*: () => import(/*...*/)

**Comment by Tarrah102** [comment]
Thanks for replying @maoberlehner definitely appreciate it. 

I think I ended up putting them in mounted as a last resort. I've tried dynamically loading these in both the template file and the main js, in exactly the way that you have above. Plus a whole bunch of ways that are listed here: https://vuejs.org/v2/guide/components-dynamic-async.html

I'm expecting to see a bunch of js files in the build assets folder, instead a just get 1 js file that is over a MB, which leads to poor performance scores. 

Is this the impact of having Storyblok?

**Comment by maoberlehner** [comment]
> I'm expecting to see a bunch of js files in the build assets folder, instead a just get 1 js file that is over a MB, which leads to poor performance scores.

This is exactly what *should* happen. I don't think it has anything to do with Storyblok. But at the same time I did not expect that using dynamic imports would not activate code-splitting.

**Comment by Tarrah102** [comment]
> > I'm expecting to see a bunch of js files in the build assets folder, instead a just get 1 js file that is over a MB, which leads to poor performance scores.
> 
> This is exactly what _should_ happen. I don't think it has anything to do with Storyblok. But at the same time I did not expect that using dynamic imports would not activate code-splitting.

Did it happen in your Storyblok site? I'm yet to find an example of code splitting when Storyblok and Gridsome come together.

**Comment by maoberlehner** [comment]
My Storyblok and Gridsome article is pretty outdated, I fear. But the code-splitting part of things has nothing to do with Storyblok. So I would be really surprised to learn that Storyblok is causing the the problem here.

In your Lighthouse Screenshot, I can see that there is a file `.../js/0.e8e803ac.js` this signals to me that code-splitting is working. Code-splitting creates files with the pattern `NUMBER.HASH.js`.
I also just tried it myself on a fresh Gridsome project with the approach I showed above and everything works as expected.

The code-splitted files are located in `dist/assets/js/NUMBER.HASH.js`.

The thing is, code-splitting is no panacea to huge bundle size at all. Most simple Vue components that only render some markup and have no huge dependencies themselves are most likely only 1kb-3kb in size. So unless you have hundreds of those, they don't add that much to your 1Mb bundle size.

Please try to run the Bundle Analyzer like described in this article https://www.codegram.com/blog/improving-a-gridsome-website-performance/ Maybe you find some big dependencies you can remove or replace. Feel free to post a screenshot of the Bundle Analyzer result here, so we can look at it together.

**Comment by Tarrah102** [comment]
None of the components have any dependencies, they are all small broken down elements for example I have a rich-text components and a button component. 

Each page probably holds on average 15 components total. 

I guess I don't understand why it's only splitting into 1 file or why it says that the components in total are 450kbs when the size of my components folder is under 100kbs. 

Here is a screen grab of the Bundle Analyzer
![analyzer (1)](https://user-images.githubusercontent.com/15898755/102475326-731d1780-40a5-11eb-9fc9-1e6b80307f05.png)

**Comment by maoberlehner** [comment]
Ok, looks like only the vue-slick-carousel is code splitted.
Hard to say what the problem is without taking a closer look at the code.

**Comment by Tarrah102** [comment]
> Ok, looks like only the vue-slick-carousel is code splitted.
> Hard to say what the problem is without taking a closer look at the code.

I've sent you an invite to my repo, all the code is there. Could you possibly take a look and see if there is anything obvious? It's being depolyed the url is in the readme.

**Comment by maoberlehner** [comment]
@Tarrah102 the problem is in `src/layouts/Default.vue` of your project. You're importing all the components in this file. This cancels out the dynamic imports in `src/main.js`. Either remove the `<script>` block in your layout file. It does nothing apart from preventing code-splitting.

**Comment by Tarrah102** [comment]
@maoberlehner thanks. Slight facepalm on my behalf but thanks!
